services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    env_file:
      - ./compose/postgres.env
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./:/opt/app
      - deps:/opt/app/deps
      - build:/opt/app/_build

  db:
    image: postgres:14
    env_file:
      - ./compose/postgres.env
    volumes:
      - /var/lib/postgresql
    ports:
      - 5432

volumes:
  build: {}
  deps: {}
